# Generated by Django 2.2.7 on 2019-11-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.CharField(max_length=15, null=True)),
                ('longitude', models.CharField(max_length=15, null=True)),
                ('equip_id', models.IntegerField(null=True)),
                ('serial', models.FloatField(null=True)),
                ('v1', models.FloatField()),
                ('v2', models.FloatField()),
                ('v3', models.FloatField()),
                ('v4', models.FloatField()),
                ('v5', models.FloatField()),
                ('v6', models.FloatField()),
                ('v7', models.FloatField()),
                ('v8', models.FloatField()),
                ('v9', models.FloatField()),
                ('v10', models.FloatField()),
                ('v11', models.FloatField()),
                ('v12', models.FloatField()),
                ('v13', models.FloatField()),
                ('v14', models.FloatField()),
                ('v15', models.FloatField()),
                ('v16', models.FloatField()),
                ('v17', models.FloatField()),
                ('v18', models.FloatField()),
                ('v19', models.FloatField()),
                ('v20', models.FloatField()),
            ],
        ),
    ]
