# Generated by Django 2.2.7 on 2019-11-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('SEQ', models.AutoField(primary_key=True, serialize=False)),
                ('KEDCD', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('found_date', models.IntegerField()),
                ('company_size', models.CharField(max_length=20, null=True)),
                ('company_type', models.CharField(max_length=20)),
                ('company_zip', models.IntegerField()),
                ('company_address', models.CharField(max_length=100, null=True)),
                ('business_code1', models.CharField(max_length=10)),
                ('business_code2', models.CharField(max_length=50)),
                ('staff_update_date', models.IntegerField(null=True)),
                ('staff_number', models.IntegerField(null=True)),
                ('company_main_product', models.CharField(max_length=100, null=True)),
                ('company_tel_num', models.CharField(max_length=20, null=True)),
                ('closing_2018', models.IntegerField(null=True)),
                ('closing_2017', models.IntegerField(null=True)),
                ('closing_2016', models.IntegerField(null=True)),
                ('closing_2015', models.IntegerField(null=True)),
                ('closing_2014', models.IntegerField(null=True)),
                ('total_assets_2018', models.IntegerField(null=True)),
                ('total_liabilities_2018', models.IntegerField(null=True)),
                ('netincome_2018', models.IntegerField(null=True)),
                ('operating_profit_2018', models.IntegerField(null=True)),
                ('total_assets_2017', models.IntegerField(null=True)),
                ('total_liabilities_2017', models.IntegerField(null=True)),
                ('netincome_2017', models.IntegerField(null=True)),
                ('operating_profit_2017', models.IntegerField(null=True)),
                ('total_assets_2016', models.IntegerField(null=True)),
                ('total_liabilities_2016', models.IntegerField(null=True)),
                ('netincome_2016', models.IntegerField(null=True)),
                ('operating_profit_2016', models.IntegerField(null=True)),
                ('total_assets_2015', models.IntegerField(null=True)),
                ('total_liabilities_2015', models.IntegerField(null=True)),
                ('netincome_2015', models.IntegerField(null=True)),
                ('operating_profit_2015', models.IntegerField(null=True)),
                ('total_assets_2014', models.IntegerField(null=True)),
                ('total_liabilities_2014', models.IntegerField(null=True)),
                ('netincome_2014', models.IntegerField(null=True)),
                ('operating_profit_2014', models.IntegerField(null=True)),
                ('PO_01', models.CharField(max_length=50, null=True)),
                ('PO_02', models.CharField(max_length=50, null=True)),
                ('PO_03', models.CharField(max_length=50, null=True)),
                ('PO_01_num', models.IntegerField(null=True)),
                ('PO_02_num', models.IntegerField(null=True)),
                ('PO_03_num', models.IntegerField(null=True)),
                ('seller_01', models.CharField(max_length=50, null=True)),
                ('seller_02', models.CharField(max_length=50, null=True)),
                ('seller_03', models.CharField(max_length=50, null=True)),
                ('seller_01_num', models.IntegerField(null=True)),
                ('seller_02_num', models.IntegerField(null=True)),
                ('seller_03_num', models.IntegerField(null=True)),
                ('GPS_X', models.FloatField()),
                ('GPS_y', models.FloatField()),
            ],
        ),
    ]
