# Generated by Django 2.2.7 on 2019-11-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20191128_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='GPS_X',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='GPS_Y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
