# Generated by Django 2.2.7 on 2019-11-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20191128_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='seller_01_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='seller_02_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='seller_03_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
