# Generated by Django 2.2.7 on 2019-11-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20191128_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='PO_01_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='PO_02_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='PO_03_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
