from django.db import models

class Company(models.Model):
    # Character size variables
    COMPANY_NAME_SIZE = 50

    # Fields
    SEQ = models.AutoField(primary_key=True)
    KEDCD = models.CharField(max_length=50)
    company_name = models.CharField(max_length=COMPANY_NAME_SIZE)
    found_date = models.IntegerField(null=True, blank=True)
    company_size = models.CharField(null=True, blank=True, max_length=20)
    company_type = models.CharField(null=True, blank=True, max_length=20)
    company_zip = models.IntegerField(null=True, blank=True)
    company_address = models.CharField(null=True, blank=True, max_length=100)
    business_code1 = models.CharField(null=True, blank=True, max_length=10)
    business_code2 = models.CharField(null=True, blank=True, max_length=50)
    staff_update_date = models.IntegerField(null=True, blank=True)
    staff_number = models.IntegerField(null=True, blank=True)
    company_main_product = models.CharField(null=True, blank=True, max_length=100)
    company_tel_num = models.CharField(null=True, blank=True, max_length=20)
    closing_2018 = models.IntegerField(null=True, blank=True)
    closing_2017 = models.IntegerField(null=True, blank=True)
    closing_2016 = models.IntegerField(null=True, blank=True)
    closing_2015 = models.IntegerField(null=True, blank=True)
    closing_2014 = models.IntegerField(null=True, blank=True)
    total_assets_2018 = models.IntegerField(null=True, blank=True)
    total_liabilities_2018 = models.IntegerField(null=True, blank=True)
    netincome_2018 = models.IntegerField(null=True, blank=True)
    operating_profit_2018 = models.IntegerField(null=True, blank=True)
    total_assets_2017 = models.IntegerField(null=True, blank=True)
    total_liabilities_2017 = models.IntegerField(null=True, blank=True)
    netincome_2017 = models.IntegerField(null=True, blank=True)
    operating_profit_2017 = models.IntegerField(null=True, blank=True)
    total_assets_2016 = models.IntegerField(null=True, blank=True)
    total_liabilities_2016 = models.IntegerField(null=True, blank=True)
    netincome_2016 = models.IntegerField(null=True, blank=True)
    operating_profit_2016 = models.IntegerField(null=True, blank=True)
    total_assets_2015 = models.IntegerField(null=True, blank=True)
    total_liabilities_2015 = models.IntegerField(null=True, blank=True)
    netincome_2015 = models.IntegerField(null=True, blank=True)
    operating_profit_2015 = models.IntegerField(null=True, blank=True)
    total_assets_2014 = models.IntegerField(null=True, blank=True)
    total_liabilities_2014 = models.IntegerField(null=True, blank=True)
    netincome_2014 = models.IntegerField(null=True, blank=True)
    operating_profit_2014 = models.IntegerField(null=True, blank=True)
    PO_01 = models.CharField(null=True, blank=True, max_length=COMPANY_NAME_SIZE)
    PO_02 = models.CharField(null=True, blank=True, max_length=COMPANY_NAME_SIZE)
    PO_03 = models.CharField(null=True, blank=True, max_length=COMPANY_NAME_SIZE)
    PO_01_num = models.BigIntegerField(null=True, blank=True)
    PO_02_num = models.BigIntegerField(null=True, blank=True)
    PO_03_num = models.BigIntegerField(null=True, blank=True)
    seller_01 = models.CharField(null=True, blank=True, max_length=COMPANY_NAME_SIZE)
    seller_02 = models.CharField(null=True, blank=True, max_length=COMPANY_NAME_SIZE)
    seller_03 = models.CharField(null=True, blank=True, max_length=COMPANY_NAME_SIZE)
    seller_01_num = models.BigIntegerField(null=True, blank=True)
    seller_02_num = models.BigIntegerField(null=True, blank=True)
    seller_03_num = models.BigIntegerField(null=True, blank=True)
    GPS_X = models.FloatField(null=True, blank=True)
    GPS_Y = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.company_name